# get_kubeconfig.yml
- name: Get Cluster ID from /v3/clusters
  uri:
    url: "https://{{ rancher_hostname }}:{{ rancher_port }}/v3/clusters?name={{ cluster_name }}"
    method: GET
    headers:
      Authorization: "Bearer {{ rancher_token }}"
    validate_certs: no
    status_code: 200
  register: cluster_info_response

- name: Extract actual clusterId
  set_fact:
    actual_cluster_id: "{{ cluster_info_response.json.data[0].id }}"

- name: Get kubeconfig for the custom cluster
  uri:
    url: "https://{{ rancher_hostname }}:{{ rancher_port }}/v3/clusters/{{ actual_cluster_id }}?action=generateKubeconfig"
    method: POST
    headers:
      Authorization: "Bearer {{ rancher_token }}"
    validate_certs: no
    status_code: 200
  register: kubeconfig_response

- name: Save kubeconfig to file
  copy:
    content: "{{ kubeconfig_response.json.config }}"
    dest: "{{ cluster_name }}-kubeconfig.yaml"
    mode: '0600'

- name: Display message
  debug:
    msg: "Kubeconfig for {{ cluster_name }} has been saved to {{ cluster_name }}-kubeconfig.yaml"