apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  labels:
    environment: sit-space     # Label สำหรับจัดกลุ่มตาม environment
    team: fraud         # Label สำหรับจัดกลุ่มตามทีม
spec:
  project: default
  source:
    repoURL: http://192.168.140.91/ghb-fraud/deployment/devops-script.git
    path: sit/database/manifest
    targetRevision: rv_dc_dev
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    syncOptions:
      - CreateNamespace=true