---
# สิ่งที่เกิดขึ้นเมื่อรัน Playbook ซ้ำ:
# ครั้งแรกที่รัน: ถ้าไม่มีบรรทัด NTP= ในไฟล์ /etc/systemd/timesyncd.conf Ansible จะเพิ่มบรรทัดดังกล่าวลงไป
# ครั้งที่สองที่รัน: Ansible จะตรวจสอบไฟล์ และถ้าพบว่าบรรทัด NTP= มีอยู่แล้วและมีเนื้อหาตรงกับสิ่งที่ต้องการ Ansible จะไม่ทำการเปลี่ยนแปลงใด ๆ
# ดังนั้นการรัน Playbook ซ้ำจะไม่ทำให้บรรทัด NTP= ถูกเพิ่มซ้ำซ้อน หรือทำให้เกิดปัญหากับการตั้งค่า NTP ที่มีอยู่แล้ว
- name: Set timezone and configure time sync for multiple host groups
  hosts: 
    - spider-cicd-dev-rancher
    - spider-cicd-dev
    - spider-swimlane
    # - spider-lb-dev
    # - spider-fraud-dev
    # - spider-db-dev
    # - spider-dev-dev
    # - spider-sit-dev

  become: yes

  tasks:
    - name: Set timezone to Asia/Bangkok
      timezone:
        name: Asia/Bangkok

    - name: Ensure systemd-timesyncd is running
      systemd:
        name: systemd-timesyncd
        state: started
        enabled: yes

    - name: Configure NTP servers for systemd-timesyncd
      lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: '^NTP='
        line: 'NTP=192.168.98.253 0.ubuntu.pool.ntp.org 1.ubuntu.pool.ntp.org'
        create: yes
        state: present
      notify: restart systemd-timesyncd

    - name: Configure fallback NTP servers for systemd-timesyncd
      lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: '^FallbackNTP='
        line: 'FallbackNTP=2.ubuntu.pool.ntp.org 3.ubuntu.pool.ntp.org'
        create: yes
        state: present
      notify: restart systemd-timesyncd

  handlers:
    - name: restart systemd-timesyncd
      systemd:
        name: systemd-timesyncd
        state: restarted
