- name: Check connectivity until success
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 10
        timeout: 600  # รอได้นานสุด 10 นาที
      delegate_to: localhost  # ให้รันจากเครื่องที่รัน Ansible แทนเป้าหมาย

    - name: Ping the host
      ansible.builtin.ping:
