---
- hosts: infra-lab-cicd-dev-rancher
  vars_files:
    - vars.yml

  tasks:
    - name: Login to Rancher and get API token
      uri:
        url: "https://{{ rancher_hostname }}:{{ rancher_port }}/v3-public/localProviders/local?action=login"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          username: "admin"
          password: "{{ admin_password }}"
        validate_certs: no
        status_code: 201
        return_content: yes
      register: login_response
    
    - name: Extract Rancher API token
      set_fact:
        rancher_token: "{{ login_response.json.token }}"

    - name: Get Cluster IDs and download kubeconfig files
      include_tasks: get_kubeconfig.yml
      loop:
        - cicd-cluster
        # - database-cluster
        # - dev-cluster
        # - fraud-cluster
        # - sit-cluster
      loop_control:
        loop_var: cluster_name