---
- hosts: spider-cicd-dev-rancher
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Login to Rancher and get API token
      uri:
        url: "https://{{ rancher_hostname }}:{{ rancher_port }}/v3-public/localProviders/local?action=login"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          username: "admin"
          password: "{{ admin_password }}"
        validate_certs: no
        status_code: 201
        return_content: yes
      register: login_response

    - name: Extract Rancher API token
      set_fact:
        rancher_token: "{{ login_response.json.token }}"

    - name: Get Cluster ID from /v3/clusters
      uri:
        url: "https://{{ rancher_hostname }}:{{ rancher_port }}/v3/clusters?name=fraud-cluster"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
        status_code: 200
      register: cluster_info_response

    - name: Extract actual clusterId
      set_fact:
        actual_cluster_id: "{{ cluster_info_response.json.data[0].id }}"

    - name: Delete Rancher Cluster
      uri:
        url: "https://{{ rancher_hostname }}:{{ rancher_port }}/v3/clusters/{{ actual_cluster_id }}"
        method: DELETE
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
