---
- hosts: spider-cicd-dev-rancher
  vars_files:
    - vars.yml
  vars:
    kubeconfigs:
      # - cicd-cluster-kubeconfig.yaml
      # - database-cluster-kubeconfig.yaml
      # - dev-cluster-kubeconfig.yaml
      - fraud-cluster-kubeconfig.yaml
      # - sit-cluster-kubeconfig.yaml
    forward_ip: "192.168.140.251"

  tasks:
    - name: Set up kubeconfig file
      shell: "cp ~/{{ item }} /tmp/{{ item }} && chmod 0600 /tmp/{{ item }}"
      with_items: "{{ kubeconfigs }}"

    - name: Backup existing ConfigMap
      shell: >
        kubectl get configmap rke2-coredns-rke2-coredns -n kube-system -o yaml > /tmp/rke2-coredns-backup-{{ item }}
      environment:
        KUBECONFIG: "/tmp/{{ item }}"
      with_items: "{{ kubeconfigs }}"

    - name: Update Corefile in ConfigMap
      shell: |
        kubectl get configmap rke2-coredns-rke2-coredns -n kube-system -o json | \
        jq '.data."Corefile" |= sub("forward   . /etc/resolv.conf"; "forward   . {{ forward_ip }}")' | \
        kubectl apply -f -
      environment:
        KUBECONFIG: "/tmp/{{ item }}"
      args:
        executable: /bin/bash
      with_items: "{{ kubeconfigs }}"
    
    - name: Verify the updated ConfigMap
      command: >
        kubectl get configmap rke2-coredns-rke2-coredns -n kube-system -o yaml
      environment:
        KUBECONFIG: "/tmp/{{ item }}"
      with_items: "{{ kubeconfigs }}"
